#ifndef HOMEMONEY_TRANSPORT_RETRY_POLICY_H
#define HOMEMONEY_TRANSPORT_RETRY_POLICY_H

#include <cstdint>

#include "protocol/sync_protocol.h"

/**
 * Retry and backoff policy, shared by the native client and the Kotlin scheduler.
 *
 * Two properties matter and both are easy to get wrong:
 *
 *  1. Only transient failures are retried. Retrying a protocol mismatch or a rejected
 *     pairing just burns the budget and delays the real error by tens of seconds. The
 *     classification lives in isRetryable() in sync_protocol.h so there is exactly one
 *     table for it.
 *
 *  2. The delay is jittered. Two phones that lose Wi-Fi at the same moment - which is the
 *     normal case, they are on the same access point - would otherwise reconnect in
 *     lockstep forever. "Equal jitter" keeps a guaranteed lower bound (so a flapping link
 *     still gets time to settle) while spreading the upper half randomly.
 *
 * The Kotlin mirror is data/sync/protocol/SyncRetryPolicy.kt and both are pinned to
 * protocol/retry_vectors.txt, generated by tools/gen_frame_vectors.py.
 */
namespace homemoney::sync {

/// Tunables for one retry loop. Defaults target a flaky home Wi-Fi link.
struct RetryPolicy {
    /// Total attempts including the first one. 1 means "no retry".
    std::uint32_t maxAttempts = 4;
    /// Delay ceiling for the first retry, doubled on each subsequent retry.
    std::uint32_t baseDelayMs = 250;
    /// Hard cap so a long outage does not push the next attempt minutes away.
    std::uint32_t maxDelayMs = 8000;
};

/// Largest shift applied when computing the ceiling; beyond this the cap dominates anyway.
inline constexpr std::uint32_t kMaxBackoffShift = 16;

/**
 * Unjittered delay ceiling for a zero based retry index.
 *
 * The shift is clamped before it is applied, so a caller that passes a silly attempt
 * number gets maxDelayMs rather than undefined behaviour.
 */
constexpr std::uint32_t backoffCeilingMs(const RetryPolicy& policy, std::uint32_t retryIndex) {
    if (policy.baseDelayMs == 0) {
        return 0;
    }
    const std::uint32_t shift = retryIndex > kMaxBackoffShift ? kMaxBackoffShift : retryIndex;
    const std::uint64_t scaled =
            static_cast<std::uint64_t>(policy.baseDelayMs) << shift;
    if (scaled >= static_cast<std::uint64_t>(policy.maxDelayMs)) {
        return policy.maxDelayMs;
    }
    return static_cast<std::uint32_t>(scaled);
}

/**
 * Equal jitter delay: half the ceiling, plus a random share of the other half.
 *
 * @param randomValue any 32 bit value; the caller owns the randomness so the function
 *                    stays pure and can be pinned to golden vectors.
 */
constexpr std::uint32_t jitteredDelayMs(const RetryPolicy& policy,
                                        std::uint32_t retryIndex,
                                        std::uint32_t randomValue) {
    const std::uint32_t ceiling = backoffCeilingMs(policy, retryIndex);
    if (ceiling == 0) {
        return 0;
    }
    const std::uint32_t half = ceiling / 2u;
    const std::uint32_t span = ceiling - half;  // covers the odd-ceiling case exactly
    return half + (randomValue % (span + 1u));
}

/**
 * Whether another attempt should be made.
 *
 * @param attemptsMade attempts already completed, including the one that just failed.
 */
constexpr bool shouldRetry(const RetryPolicy& policy,
                           SyncErrorCode error,
                           std::uint32_t attemptsMade) {
    if (error == SyncErrorCode::kOk) {
        return false;
    }
    if (attemptsMade >= policy.maxAttempts) {
        return false;
    }
    return isRetryable(error);
}

/**
 * Small deterministic PRNG for jitter.
 *
 * std::rand is not thread safe and pulling in <random> for one number is overkill;
 * xorshift32 is three instructions and, being pure, can be verified at compile time.
 * Seeded per connection attempt from the monotonic clock in the caller.
 */
constexpr std::uint32_t xorshift32(std::uint32_t state) {
    state ^= state << 13;
    state ^= state >> 17;
    state ^= state << 5;
    return state;
}

// A zero seed is a fixed point of xorshift32, so callers must avoid it. Guard here rather
// than trusting every call site to remember.
constexpr std::uint32_t nextRandom(std::uint32_t& state) {
    if (state == 0) {
        state = 0x9E3779B9u;
    }
    state = xorshift32(state);
    return state;
}

}  // namespace homemoney::sync

#endif  // HOMEMONEY_TRANSPORT_RETRY_POLICY_H
