package com.chronie.homemoney.data.sync.protocol

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Cross-language conformance: the Kotlin codec must produce exactly the same bytes as the
 * C++ codec.
 *
 * Both sides are checked against one shared file, `app/src/main/cpp/protocol/frame_vectors.txt`,
 * which is generated by `tools/gen_frame_vectors.py` - a third, independent implementation
 * of the spec. That matters: if the vectors were dumped from either production codec, a
 * bug present in that codec would silently bless itself.
 *
 * The C++ half of this check lives in `protocol/protocol_conformance.cpp` and runs as
 * static_asserts during the native build.
 */
class ProtocolConformanceTest {

    private data class Vector(
        val name: String,
        val version: Int,
        val opcode: Int,
        val flags: Int,
        val sessionId: Long,
        val seq: Int,
        val payload: ByteArray,
        val expectedHeader: ByteArray
    )

    private val vectors: List<Vector> by lazy { loadVectors() }

    // ------------------------------------------------------------------- tests

    @Test
    fun `golden vector file is present and non trivial`() {
        assertTrue(
            "expected at least 10 vectors, found ${vectors.size}. " +
                    "Run: python tools/gen_frame_vectors.py",
            vectors.size >= 10
        )
    }

    @Test
    fun `every vector encodes to the exact golden bytes`() {
        for (v in vectors) {
            val encoded = SyncWireProtocol.encodeHeader(
                FrameHeader(
                    version = v.version,
                    opcode = SyncOpcode.fromValue(v.opcode)!!,
                    flags = v.flags,
                    sessionId = v.sessionId,
                    seq = v.seq,
                    payloadLen = v.payload.size,
                    payloadCrc32 = Crc32c.compute(v.payload)
                )
            )
            assertEquals(
                "vector '${v.name}' encodes differently than the shared golden bytes",
                v.expectedHeader.toHex(),
                encoded.toHex()
            )
        }
    }

    @Test
    fun `every vector decodes back to its original fields`() {
        for (v in vectors) {
            val result = SyncWireProtocol.decodeHeader(v.expectedHeader)
            assertTrue("vector '${v.name}' failed to decode: $result", result is FrameDecodeResult.Success)

            val header = (result as FrameDecodeResult.Success).header
            assertEquals("${v.name}: version", v.version, header.version)
            assertEquals("${v.name}: opcode", v.opcode, header.opcode.value)
            assertEquals("${v.name}: flags", v.flags, header.flags)
            assertEquals("${v.name}: sessionId", v.sessionId, header.sessionId)
            assertEquals("${v.name}: seq", v.seq, header.seq)
            assertEquals("${v.name}: payloadLen", v.payload.size, header.payloadLen)
            assertEquals(
                "${v.name}: payloadCrc32",
                Crc32c.compute(v.payload),
                header.payloadCrc32
            )
        }
    }

    @Test
    fun `full frame encoding matches golden header followed by the payload`() {
        for (v in vectors) {
            val frame = SyncWireProtocol.encodeFrame(
                opcode = SyncOpcode.fromValue(v.opcode)!!,
                payload = v.payload,
                flags = v.flags,
                sessionId = v.sessionId,
                seq = v.seq
            )
            assertEquals(
                "vector '${v.name}' frame length",
                SyncWireProtocol.HEADER_SIZE + v.payload.size,
                frame.size
            )
            assertEquals(
                "vector '${v.name}' frame bytes",
                (v.expectedHeader + v.payload).toHex(),
                frame.toHex()
            )
        }
    }

    @Test
    fun `constants declared on both sides agree with the vector file`() {
        // The magic and version are embedded in every golden header, so reading them back
        // out catches a constant that was changed on only one side.
        for (v in vectors) {
            assertEquals(
                "vector '${v.name}' magic",
                SyncWireProtocol.MAGIC,
                v.expectedHeader.readIntAt(0)
            )
            assertEquals(
                "vector '${v.name}' version",
                SyncWireProtocol.PROTOCOL_VERSION,
                v.version
            )
        }
        assertEquals(32, SyncWireProtocol.HEADER_SIZE)
        assertEquals(1_048_576, SyncWireProtocol.MAX_PAYLOAD_SIZE)
    }

    // ----------------------------------------------------------------- loading

    private fun loadVectors(): List<Vector> {
        val file = locateVectorFile()
        return file.readLines()
            .map(String::trim)
            .filter { it.isNotEmpty() && !it.startsWith("#") }
            .map { line ->
                val parts = line.split("|")
                require(parts.size == 8) { "malformed vector line: $line" }
                Vector(
                    name = parts[0],
                    version = parts[1].toInt(16),
                    opcode = parts[2].toInt(16),
                    flags = parts[3].toInt(16),
                    sessionId = parts[4].toULong(16).toLong(),
                    seq = parts[5].toUInt().toInt(),
                    payload = parts[6].fromHex(),
                    expectedHeader = parts[7].fromHex()
                )
            }
    }

    /**
     * Unit tests run with the module directory as the working directory, but resolving
     * upwards as well keeps the test green when it is launched from the IDE with a
     * different root.
     */
    private fun locateVectorFile(): File {
        val relative = "app/src/main/cpp/protocol/frame_vectors.txt"
        var dir: File? = File(".").absoluteFile
        while (dir != null) {
            for (candidate in listOf(File(dir, relative), File(dir, relative.removePrefix("app/")))) {
                if (candidate.isFile) return candidate
            }
            dir = dir.parentFile
        }
        throw AssertionError(
            "could not locate $relative from ${File(".").absolutePath}. " +
                    "Run: python tools/gen_frame_vectors.py"
        )
    }

    private fun String.fromHex(): ByteArray {
        require(length % 2 == 0) { "odd length hex string: $this" }
        return ByteArray(length / 2) { i ->
            substring(i * 2, i * 2 + 2).toInt(16).toByte()
        }
    }

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }

    private fun ByteArray.readIntAt(offset: Int): Int =
        ((this[offset].toInt() and 0xFF) shl 24) or
                ((this[offset + 1].toInt() and 0xFF) shl 16) or
                ((this[offset + 2].toInt() and 0xFF) shl 8) or
                (this[offset + 3].toInt() and 0xFF)
}
